apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *" # 분(0-59), 시(0-23), 일(1-31), 월(1-12), 요일(0-7)
  jobTemplate:
    spec: # job spec
      template:
        spec: # pod spec
          containers:
            - name: hello
              image: docker.io/busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes Cluster
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
