apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-pod
spec:
  containers:
    - name: busybox
      image: docker.io/busybox
      args: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: hostpath-volume
          mountPath: /etc/data
  imagePullSecrets:
    - name: regcred
  volumes:
    - name: hostpath-volume
      hostPath:
        path: /tmp
