apiVersion: v1
kind: Pod
metadata:
  name: nfs-volume-pod
spec:
  containers:
    - name: nfs-volume-container
      image: docker.io/busybox
      args: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt
  imagePullSecrets:
    - name: regcred
  volumes:
    - name: nfs-volume
      nfs:
        path: /
        server: 172.17.57.17 # nfs-service서비스의 cluster-ip주소
