apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-persistentvolume-recycle
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle ### 추가
  nfs:
    path: /
    server: { CLUSTER-IP }
