apiVersion: batch/v1
kind: Job
metadata:
  name: primenumber-job
spec:
  template:
    spec:
      containers:
        - name: primenumber-generator
          image: docker.io/gnstkd/primenumber_generator:1.0
          env:
            - name: A_START_NUM
              value: "2"
            - name: A_SIZE_NUM
              value: "10**6"
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
  backoffLimit: 4
