apiVersion: v1
kind: Pod
metadata:
  name: cm-to-env-selective
spec:
  containers:
    - name: my-container
      image: docker.io/busybox
      args: ["tail", "-f", "/dev/null"]
      env:
        - name: NEW_LOG_LEVEL ## 새롭게 설정할 환경변수의 이름
          valueFrom:
            configMapKeyRef:
              name: log-level-configmap ## 참조할 컨피그맵의 이름
              key: LOG_LEVEL ## 가져올 데이터의 키
        - name: NEW_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: config-k8s
              key: container
