apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 80
  selector:
    app: blue-green-deployment
    version: v1.17
