apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume-pod
spec:
  containers:
    - name: content-creator
      image: docker.io/busybox
      args: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: emptydir-volume
          mountPath: /data
    - name: webserver
      image: docker.io/httpd:2
      volumeMounts:
        - name: emptydir-volume
          mountPath: /usr/local/apache2/htdocs/
  imagePullSecrets:
    - name: regcred
  volumes:
    - name: emptydir-volume
      emptyDir: {}
