apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-persistentvolume-delete
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete ### 추가
  nfs:
    path: /
    server: { CLUSTER-IP }
