apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
spec:
  containers:
  - name: my-nginx-container
    image: docker.io/nginx:latest              # <<< 레지스트리를 명시
    ports:
    - containerPort: 80
      protocol: TCP
  - name: ubuntu-sidecar-container
    image: docker.io/alicek106/rr-test:curl    # <<< 레지스트리를 명시
    command: ["tail"]
    args: ["-f", "/dev/null"]
  imagePullSecrets:                            # <<< 이미지를 가져올 때 사용할 크리덴셜을 지정
  - name: regcred 