apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-flask-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: whoami-flask
  template:
    metadata:
      name: whoami-flask-pod
      labels:
        app: whoami-flask
    spec:
      containers:
        - name: whoami-flask-container
          image: docker.io/gnstkd/whoami-flask:v1
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-flask-service
spec:
  type: LoadBalancer
  ports:
    - name: whoami-flask
      port: 5000
      targetPort: 5000
  selector:
    app: whoami-flask
