apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-volume
spec:
  storageClassName: "my-storage-class"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /
    server: 172.17.23.198 # nfs-service 의 CLUSTER-IP
