apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: ClusterIP
  selector:
    app: web1
  ports:
    - name: service-port
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: ClusterIP
  selector:
    app: web2
  ports:
    - name: service-port
      port: 9090
      targetPort: 80
