apiVersion: v1
kind: Pod
metadata:
  name: secret-env-from-all
spec:
  containers:
    - name: my-container
      image: docker.io/busybox
      args: ["tail", "-f", "/dev/null"]
      envFrom:
        - secretRef:
            name: my-password
