apiVersion: v1
kind: Pod
metadata:
  name: secret-env-from-selective
spec:
  containers:
    - name: my-container
      image: docker.io/busybox
      args: ["tail", "-f", "/dev/null"]
      env:
        - name: YOUR_PASSWORD ## 새로운 환경변수 이름을 설정
          valueFrom:
            secretKeyRef:
              name: our-password ## 값을 가져올 시크릿을 지정
              key: pw2 ## 값을 가져올 시크릿의 키를 지정
