apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
    - name: busybox
      image: docker.io/busybox:1
      command: ["sh", "-c", "sleep 30; exit 0"]
  restartPolicy: Always
  imagePullSecrets:
    - name: regcred
