apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sample-daemonset-rollingupdate
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx-container
          image: docker.io/nginx:1.16
      imagePullSecrets:
        - name: regcred
